root: true

extends:
  - prettier

plugins:
  - prettier

parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    modules: true
    jsx: true
    experimentalObjectRestSpread: true

env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true

rules:
  # Possible Errors
  comma-dangle: [2, only-multiline]
  no-cond-assign: 2
  no-console: 0
  no-constant-condition: 2
  no-control-regex: 2
  no-debugger: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty: 2
  no-empty-character-class: 2
  no-ex-assign: 2
  no-extra-boolean-cast: 2
  no-extra-parens: 0
  no-func-assign: 2
  no-inner-declarations: [2, functions]
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-negated-in-lhs: 2
  no-obj-calls: 2
  no-regex-spaces: 2
  no-sparse-arrays: 2
  no-unreachable: 2
  use-isnan: 2
  valid-jsdoc: 0
  valid-typeof: 2

  # Best Practices
  accessor-pairs: 2
  block-scoped-var: 0
  complexity: 0
  consistent-return: 0
  curly: 0
  default-case: 0
  dot-location: 0
  dot-notation: 0
  eqeqeq: [2, "allow-null"]
  guard-for-in: 0
  no-alert: 0
  no-caller: 2
  no-case-declarations: 2
  no-div-regex: 2
  no-else-return: 0
  no-empty-pattern: 2
  no-eq-null: 0
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-fallthrough: 2
  no-floating-decimal: 0
  no-implicit-coercion: 0
  no-implied-eval: 2
  no-invalid-this: 0
  no-iterator: 2
  no-labels: 0
  no-lone-blocks: 2
  no-loop-func: 2
  no-magic-number: 0
  no-multi-spaces: 0
  no-multi-str: 0
  no-native-reassign: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-new: 2
  no-octal-escape: 2
  no-octal: 2
  no-proto: 2
  no-redeclare: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 0
  no-throw-literal: 0
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-void: 2
  no-warning-comments: 0
  no-with: 2
  radix: 2
  vars-on-top: 0
  yoda: 0

  # Strict
  strict: 0

  # Variables
  init-declarations: 0
  no-catch-shadow: 2
  no-delete-var: 2
  no-label-var: 2
  no-shadow-restricted-names: 2
  no-shadow: 0
  no-undef-init: 2
  no-undef: 0
  no-undefined: 0
  no-unused-vars: [2, { varsIgnorePattern: "^_", argsIgnorePattern: "^_" }]
  no-use-before-define: 0

  # Node.js and CommonJS
  callback-return: 2
  global-require: 2
  handle-callback-err: 2
  no-mixed-requires: 0
  no-new-require: 0
  no-path-concat: 2
  no-process-exit: 2
  no-restricted-modules: 0
  no-sync: 0

  # ECMAScript 6
  arrow-body-style: 0
  arrow-parens: 0
  arrow-spacing: 2
  constructor-super: 0
  no-arrow-condition: 0
  no-class-assign: 0
  no-const-assign: 2
  no-dupe-class-members: 0
  no-this-before-super: 0
  no-var: 0
  object-shorthand: 0
  prefer-arrow-callback: 0
  prefer-const: 2
  prefer-reflect: 0
  prefer-spread: 0
  prefer-template: 0
  require-yield: 0

  prettier/prettier:
    - 'error'
    - singleQuote: true
      printWidth: 100
